### PR TITLE
If you're going to do something you best do it right

### PR DESCRIPTION
**Pull request by anomaly256**
;)

### CODE REVIEW

**Comment by wikkyk** [comment]
The compiler adds an implicit `return 0;` at the end of `main()` in C99.

**Comment by wikkyk** [comment]
REJECTED mwahahah

**Comment by anomaly256** [comment]
Thats just lazeh

**Comment by anomaly256** [comment]
apparently it returns '50' not '0' here

**Comment by anomaly256** [comment]
Provide a makefile that specifies c99 mode

**Comment by wikkyk** [comment]
No, who cares.

**Pull request closed without merging**
